# Generated by Django 5.0.6 on 2025-11-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_managers_alter_user_groups"),
        ("core", "0004_onboardingprofile_patient_is_onboarding_complete"),
    ]

    operations = []
