# Generated by Django 5.0.6 on 2025-11-13 18:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_merge_20251112_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.Report.report_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="pdf_url",
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
